### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by Warmsodas** [eTzmNcbkrng/SavedInstances#37]
Any idea on what is causing this?

https://gyazo.com/c0c63d2a4d6fb7c23e267670570873b1 when i install the latest version off curse 7.0.8 it works fine, but when i tried the latest one this happens

**Comment by DesertDog1178** [comment]
I just started having this issue too

**Comment by DesertDog1178** [comment]
Is now the error I get:

`Message: Interface\AddOns\SavedInstances\SavedInstances.lua:4202: attempt to concatenate local 'kabbrev' (a nil value)
Time: 09/13/17 06:57:50
Count: 7
Stack: Interface\AddOns\SavedInstances\SavedInstances.lua:4202: attempt to concatenate local 'kabbrev' (a nil value)
[C]: ?
Interface\AddOns\SavedInstances\SavedInstances.lua:4202: in function `ShowTooltip'
Interface\AddOns\SavedInstances\SavedInstances.lua:2682: in function <Interface\AddOns\SavedInstances\SavedInstances.lua:2680>
Interface\AddOns\Titan\LDBToTitan.lua:327: in function <Interface\AddOns\Titan\LDBToTitan.lua:286>

Locals: `

**Comment by Carrybag1** [comment]
This is because you or one of your characters have the new dungeon keystone.

I'm not entirely sure if the abbreviations point to anything but I added my own and it appears to be working fine.

Working solution - add in savedisntances.lua

Add below line 64          [235] = L["SotT"],
add below line 80          ["Seat of the Triumvirate"] = L["SotT"],
