### ISSUE TITLE
[Request] Contract or truncate the MythicKeystone text.

### ISSUE THREAD

**Issue by Pariah** [eTzmNcbkrng/SavedInstances#8]
I was wondering if it would be possible to shorten the name of keys with regards to the current keystone each toon has. It takes up a lot of space and expands the character section longer than most.

For example: "Return to Karazhan: Lower(7) could be converted to "L Kara 7" perhaps. Or something thereabout.

I have included a screenshot to illustrate the point. I am quite the ALToholic.

![savedinstances](https://user-images.githubusercontent.com/616394/26862274-df60d5a8-4b17-11e7-940e-42441f25831a.jpg)

P.S. As an side, is it possible to disable the Emissary lines somewhere? I'm having a hard time finding them.
P.P.S. Thank you very, very much for keeping this addon working and up-to-date. Many of us appreciate it.

**Comment by eTzmNcbkrng** [comment]
I've added some truncated Dungeon names in the [ShortNames](https://github.com/eTzmNcbkrng/SavedInstances/tree/ShortNames) branch. 
This was a bit of a struggle because although ZoneIDs are available on WoWHead with next to no effort, these are not the same as Dungeon MapIDs.
I hope I got the MapIDs correct but I have no way of knowing, I was also only able to find one reference for Kara, but I'm sure there are multiple Kara dungeons.
In this branch the short names are enabled by default and can be switched off through the interface settings, the short names I chose are completely arbitrary and there is no way to change them in game. For now, adding the ability to change them in game is beyond my abilities, I'm truly learning this as I go.

I'll look at adding an option to disable Emissary caches (should be too hard, just requires thought around reorganising the layout of the settings interface), for now the easiest way to disable them is probably to change your SavedInstances.lua config file in the WTF SavedVariables folder.  
Change this line `["DailyWorldQuest"] = true,` to this `["DailyWorldQuest"] = false,`.

**Comment by rhyokin** [comment]
I tried the shortnames branch but it didn't actually make any changes besides providing the interface option, oddly enough.  The ability to disable m+ tracking would be useful.

**Comment by eTzmNcbkrng** [comment]
If you changed line 698 and 699 then you were editing the wrong file. You were modifying the addon's code. I was referring to your personalised config file, which is located at `Path\To\Warcraft\WTF\Account\$Account\$Realm\SavedVariables\SavedInstances.lua`.

If you reordered the currencies and it broke, you probably forgot a comma, I do this constantly lol.

I've not been in game for a while but next time I am I'll try to get into a Mythic group so I actually have a keystone to play around with.

Thanks for your feedback.

**Comment by AlexAtTheBux** [comment]
If you want to add the option to disable tracking Emissary quests, open config.lua and make this addition at line 374:
```lua
          DailyWorldQuest = {
            type = "toggle",
            order = 33.6,
            name = L["Emissary quests"],
          },
```

The in the locale.lua file, add this (I added it at line 62, but it can be anywhere in the first block of localized strings): 
```lua
Ld["Emissary quests"] = "Emissary quests"
```
This will add the checkbox on SavedInstances' config panel to track Emissary quests.

**Comment by DesertDog1178** [comment]
I tried using the short names, but it didn't change anything when I installed it.

**Comment by AlexAtTheBux** [comment]
OK, so I got everything to work properly with shortening keystone names, toggling the display of emissaries/keystones, and toggling the shortening of keystones.  The files I'm attaching also include the fix for Tomb of Sargeras and my update for Emissaries.

* Keystones
  * Option to display verbose names ("Lower Karazhan (7)", "Darkheart Thicket (13)") or abbreviated names ("Kara L (7)", "DHT (13)")
  * Added spaces in "Mythic Keystone" and between the dungeon name and level

* Emissaries
  * Display a check mark if the character has already completed that quest or a question mark if the quest is ready to turn in
  * Added spaces between the faction name and the number of days remaining, and between the number and "days"
  * Default to "Unknown Emissary" if daily reset occurs and the available emissary quests aren't visible to the active character
    * This can be due to the character not having WQs unlocked or the character having already completed the emissaries prior to loading the addon.

* Raids
  * Enable display of Tomb of Sargeras lockouts
  * Temporary update for ToS LFR lockouts.
    * This will need to be adjusted over the course of the next 6-8 weeks as the LFR wings unlock and actual data becomes available
  * Add "altid"s for the three WoD raids. These should be the values for the LFR versions you enter from your Garrison.

[SavedInstances.zip](https://github.com/eTzmNcbkrng/SavedInstances/files/1092847/SavedInstances.zip)

**Comment by stevietv** [comment]
I can't download the zip, has an error unzipping

**Comment by digitalellis** [comment]
I was able to download the .zip and tried it out but get the following error now.
<spoiler>
SavedInstances\SavedInstances-7.0.8.lua:4182: attempt to concatenate field 'abbrev' (a nil value)
SavedInstances\SavedInstances-7.0.8.lua:4182: in function `ShowTooltip'
SavedInstances\SavedInstances-7.0.8.lua:2666: in function `OnEnter'
</spoiler>

**Comment by AlexAtTheBux** [comment]
@digitalellis - this probably happened because one of the other toons you have saved hasn't updated their keystone info since you updated the addon. I forgot to make it backwards compatible, so any toon that has a keystone needs to log in once to clear that error.  After that it should be fine. My mistake, I'll fix it in a little bit.

@stevietv - I'm 100% not knowledgeable on using github or I'd upload the files themselves here.  Working on that.  What error is the zip file giving you?

**Comment by ceylina** [comment]
7zip is giving me this as the error
"Can not open the file as a zip archive, the file is open as a rar archive. "
It looks like it is not a proper zip file. If I open it in the GUI for 7zip and select extract, it can extract but trying to context menu extract it is not working.

**Comment by AlexAtTheBux** [comment]
@digitalellis and @stevietv - I have my own fork of SavedInstances now, [located here](https://github.com/AlexAtTheBux/SavedInstances/tree/master/SavedInstances). This should eliminate the need for unzipping it, and will also allow me to make changes as they come up (like for ToS LFRs
@ceylina - That's my fault, I use WinRAR for all of my archiving and just renamed it as a .zip after it archived.  Didn't realize it would cause an issue, as WinRAR can open .rar files that are renamed .zip.  Anyway, the fork I created will eliminate that.

Also, now that I have a fork, can someone send me dinner?

**Comment by digitalellis** [comment]
@AlexAtTheBux - Thank you sir. Tried out the new code and it works perfectly! Dinner is on its way ;D

**Comment by Stanzilla** [comment]
@AlexAtTheBux are you going to make a Pull Request for those changes?

**Comment by AlexAtTheBux** [comment]
@Stanzilla I think I just did.  GitHub is new territory for me.
